apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-sa
  namespace: security-lab
  annotations:
    azure.workload.identity/client-id: "a768c68e-b426-4505-b20a-d131cbe7d2c4"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
  namespace: security-lab
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "a768c68e-b426-4505-b20a-d131cbe7d2c4"
    keyvaultName: "kv-aks-lab-93fda156"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""
    tenantId: "9f0a1a4c-4f45-41ba-b50b-63f7aaa140bd"